channels:
  - conda-forge
  - intel
  - saedrna
  - defaults

dependencies:
  - assimp
  - blas * openblas
  - boost-cpp
  - capstone
  - catch2
  - cereal
  - ceres-solver
  - cgal-cpp
  - cmake
  - eigen
  - embree3
  - entwine
  - geogram
  - geographiclib 1.50 he1b5a44_1000
  - gflags
  - glew
  - glfw
  - glm
  - glog
  - ipp-include
  - ipp-static
  - laszip
  - libblas
  - libcblas
  - libgdal
  - liblapacke
  - libtiff
  - ninja
  - ocl-icd
  - open3d 0.12.0 h9c3ff4c_1001
  - opencv
  - openexr
  - openmvg 1.6 h859e10a_1001
  - openscenegraph
  - pcl
  - pdal
  - proj
  - qt
  - suitesparse
  - tbb
  - tbb-devel
  - xerces-c
  - gcc_linux-64                  # [linux]
  - gxx_linux-64                  # [linux]
  - ocl-icd                       # [linux]
  - gcc_linux-64                  # [linux]
  - gxx_linux-64                  # [linux]
  - ocl-icd                       # [linux]
  - libselinux-cos6-x86_64        # [linux]
  - libx11-cos6-x86_64            # [linux]
  - libxau-cos6-x86_64            # [linux]
  - libxcb-cos6-x86_64            # [linux]
  - libxdamage-cos6-x86_64        # [linux]
  - libxext-cos6-x86_64           # [linux]
  - libxfixes-cos6-x86_64         # [linux]
  - libxxf86vm-cos6-x86_64        # [linux]
  - mesa-dri-drivers-cos6-x86_64  # [linux]
  - mesa-libgl-devel-cos6-x86_64  # [linux]
