{% set version = "0.12.0" %}

package:
  name: open3d
  version: {{ version }}

source:
  - git_url: https://github.com/intel-isl/Open3D
  - git_rev: v0.12.0

build:
  number: 1000
  skip: true # [not win]

requirements:
  build:
    - cmake
    - ninja
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}

  host:
    - eigen 3.3.9
    - flann
    - glew
    - glfw
    - libjpeg-turbo
    - libpng
    - zlib
    - pybind11 

  run:
    - eigen 3.3.9
    - flann
    - glew
    - glfw
    - libjpeg-turbo
    - libpng
    - zlib

about:
  home: http://www.open3d.org
  license: MIT
  summary: Open3D, A Modern Library for 3D Data Processing
  license_file: LICENSE

extra:
  recipe-maintainers:
    - saedrna