{% set version = "0.12.0" %}

package:
  name: open3d
  version: {{ version }}

source:
  - git_url: https://github.com/intel-isl/Open3D
  - git_rev: v0.12.0

build:
  number: 1001

requirements:
  build:
    - cmake
    - ninja
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ cdt('xorg-x11-proto-devel') }}  # [linux]
    - {{ cdt('libx11-devel') }}          # [linux]
    - {{ cdt('libxext-devel') }}         # [linux]
    - {{ cdt('libxrender-devel') }}      # [linux]
    - {{ cdt('mesa-libgl-devel') }}      # [linux]
    - {{ cdt('mesa-libegl-devel') }}     # [linux]
    - {{ cdt('mesa-dri-drivers') }}      # [linux]
    - {{ cdt('libxau-devel') }}          # [linux]
    - {{ cdt('alsa-lib-devel') }}        # [linux]
    - {{ cdt('libdrm-devel') }}          # [linux]
    - {{ cdt('libxcomposite-devel') }}   # [linux]
    - {{ cdt('libxcursor-devel') }}      # [linux]
    - {{ cdt('libxi-devel') }}           # [linux]
    - {{ cdt('libxrandr-devel') }}       # [linux]
    - {{ cdt('libxscrnsaver-devel') }}   # [linux]
    - {{ cdt('libxtst-devel') }}         # [linux]
    - {{ cdt('libselinux-devel') }}      # [linux]
    - {{ cdt('libxdamage') }}            # [linux]
    - {{ cdt('libxdamage-devel') }}      # [linux]
    - {{ cdt('libxfixes') }}             # [linux]
    - {{ cdt('libxfixes-devel') }}       # [linux]
    - {{ cdt('libxxf86vm') }}            # [linux]

  host:
    - eigen 3.3.9
    - flann
    - glew
    - glfw
    - libjpeg-turbo
    - libpng
    - zlib
    - pybind11
    - freetype
     
  run:
    - eigen 3.3.9
    - flann
    - glew
    - glfw
    - libjpeg-turbo
    - libpng
    - zlib
    - freetype

about:
  home: http://www.open3d.org
  license: MIT
  summary: Open3D, A Modern Library for 3D Data Processing
  license_file: LICENSE

extra:
  recipe-maintainers:
    - saedrna