{% set version = "0.1.0" %}

package:
  name: teaserpp
  version: {{ version }}

source:
  - git_url: https://github.com/saedrna/TEASERPP
  - git_rev: f1516af9a1eb8eb1e9c3c5120edbb0da73ec0f75

build:
  number: 1000

requirements:
  build:
    - cmake
    - ninja
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}

  host:
    - eigen 3.3.9
     
  run:
    - eigen 3.3.9

about:
  home: https://github.com/MIT-SPARK/TEASER-plusplus
  license: MIT
  summary: TEASER++ fast & certifiable 3D registration
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - saedrna