{% set version = "1.7.12" %}

package:
  name: alembic
  version: {{ version }}

source:
  - url: https://github.com/alembic/alembic/archive/{{ version }}.tar.gz
    fn: alembic-{{ version }}.tar.gz
    sha256: 6c603b87c9a3eaa13618e577dd9ef5277018cdcd09ac82d3c196ad8bed6a1b48

build:
  number: 1000

requirements:
  build:
    - cmake
    - ninja
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - openexr
    - zlib
  run: 
    - openexr
    - zlib

about:
  home: http://www.alembic.io/
  license: MIT
  license_file: LICENSE.txt
  summary: Alembic is an open computer graphics interchange framework.

extra:
  recipe-maintainers:
    - saedrna
